import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import StartChat from '../components/StartChat'


export default function Home() {
  return (
    <div className='homepage'>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Sidebar minDisplay="block" width="100%"/>
    <StartChat />
    </div>
  )
}
